
# netlify.toml - Configuración para Múltiples Entornos

# Regla para el entorno de PRODUCCIÓN (rama "main")
[context.production]
  [[redirects]]
    from = "/api/*"
    to = "https://script.google.com/macros/s/AKfycbznLvaaiQDi6ouVpPEn97bXU7ubcdrHAnYYVRP9L0Ie5psTyte3FZXX4HEr7PfYW_Auqg/exec"
    status = 200

# Regla para el entorno de DESARROLLO (rama "develop")
# También se aplicará a todas las demás ramas que no sean "main"
[context.branch-deploy]
  [[redirects]]
    from = "/api/*"
    to = "https://script.google.com/macros/s/AKfycbwbhKnHUfqXLBtic9RTZb5tDh2A8DDMI5M4Tswg9jqHUHvTOVBuWgalMFJwxQ35fUPvkA/exec"
    status = 200